#!/usr/bin/env bash
draw() {
    kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$1" </dev/null >/dev/tty
}

file=$1
w=$2
h=$3
x=$4
y=$5

cache_d="$HOME/.cache/lf_previews"

if [[ ! -d "$cache_d" ]]; then mkdir "$cache_d"; fi

ext=".${file##*.}"

exiftype="$(exiftool -s3 -MIMEType "$file")"
filetype="$(file -Lb --mime-type "$file")"

if [[ "$filetype" =~ ^image ]]; then
    draw "$file"
    exit 1
fi

if [[ "$filetype" == "application/pdf" ]]; then
    cache_f="${cache_d}/${ext}_preview"
    pdftoppm -f 1 -l 1 \
        -scale-to-x 1920 \
        -scale-to-y -1 \
        -singlefile \
        -jpeg \
        -- "$file" "$cache_f" && mv -- "$cache_f.jpg" "$cache_f"

    draw "$cache_f"
    rm -f "$cache_f"
    exit 1
fi

if [[ "$exiftype" =~ ^video ]]; then
    # vidthumb is from here:
    # https://raw.githubusercontent.com/duganchen/kitty-pistol-previewer/main/vidthumb
    draw "$(vidthumb "$file")"
    exit 1
fi

if [[ "$exiftype" =~ ^audio ]]; then
    cache_f="${cache_d}/${ext}_preview"
    [[ "$ext" == .m4a ]] && covertag=coverart || covertag=Picture
    exiftool -b -"$covertag" "$file" >"$cache_f"

    draw "$cache_f"
    rm -f "$cache_f"
    exit 1
fi

#"$HOME/.config/lf/ranger/scope.sh" "$file" "$w" "$h" "" "" || true
pistol -- "$file" "$w"
