#!/usr/bin/env bash
draw() {
	kitten icat --stdin no --transfer-mode memory --place "${w}x${h}@${x}x${y}" "$1" </dev/null >/dev/tty
	[[ -f "$cache_f" ]] && rm -f "$cache_f"
	exit 1
}

file=$1
w=$2
h=$3
x=$4
y=$5

cache_d="$HOME/.cache/lf_previews"
if [[ ! -d "$cache_d" ]]; then mkdir "$cache_d"; fi

ext="${file##*.}"
cache_f="${cache_d}/${ext}_preview"

exiftype="$(exiftool -s3 -MIMEType "$file")"
filetype="$(file -Lb --mime-type "$file")"

if [[ "$filetype" =~ ^image ]]; then
	draw "$file"

elif [[ "$filetype" == "application/pdf" ]]; then
	pdftoppm -f 1 -l 1 \
		-scale-to-x 1920 \
		-scale-to-y -1 \
		-singlefile \
		-jpeg \
		-- "$file" "$cache_f" && mv -- "${cache_f}.jpg" "$cache_f"

	draw "$cache_f"

elif [[ "$filetype" =~ ^application/epub ]]; then
	epub-thumbnailer "$file" "$cache_f" "$((w * h))"
	draw "$cache_f"

elif [[ "$exiftype" =~ ^video ]]; then
	draw "$(vidthumb "$file")"

elif [[ "$exiftype" =~ ^audio ]]; then
	[[ "$ext" == m4a ]] && covertag=coverart || covertag=Picture
	exiftool -b -"$covertag" "$file" >"$cache_f"

	draw "$cache_f"
fi

#"$HOME/.config/lf/ranger/scope.sh" "$file" "$w" "$h" "" "" || true
pistol -- "$file" "$w"
