#!/bin/bash

shopt -s extglob

help() {
    "$@" --help 2>&1 | bathelp
}

autocookie() {
    sleep 1
    while true; do xdotool click --delay 5 --repeat 10000 1; done
}

dotconf-add() {
    local conf
    for conf in "$@"; do
        local file pattern
        [[ ! -e "$conf" ]] && printf "File doesn't exist\n" && return 1
        file=${conf%%+(/)}
        file=${file##*/}
        [[ -d "$conf" ]] && file=${file}/
        pattern='!'"/${file}"
        if ! grep -Fxq "$pattern" "$HOME"/.config/.gitignore; then
            printf "%s\n" "$pattern" >>"$HOME"/.config/.gitignore
            dotfiles add "$HOME"/.config/.gitignore
        fi
        dotfiles add "$conf"
    done
}

dotbranch-mergeall() {
    local branch branch_name
    branch_name="$(dotfiles rev-parse --abbrev-ref HEAD)"
    if [[ "$branch_name" != "master" ]]; then
        printf '%s\n' "Error: Current branch is not master"
    else
        while read -r branch; do
            if [[ "$branch" != "master" ]]; then
                (
                    dotfiles checkout "$branch"
                    dotfiles show
                    printf '%s\n>> ' "Confirm push? [y/N] (Please review carefully)"
                    read -r confirm_push
                    if [[ "$confirm_push" =~ ^[Yy]$ ]]; then
                        dotfiles merge master
                        dotfiles push
                    fi
                )
                dotfiles checkout master
            fi
        done < <(dotfiles for-each-ref --format='%(refname:short)' refs/heads/)
    fi
}
