#!/bin/bash

shopt -s extglob

help() {
    "$@" --help 2>&1 | bathelp
}

autocookie() {
    sleep 1
    while true; do xdotool click --delay 5 --repeat 10000 1; done
}

dotconf-add() {
    local conf
    for conf in "$@"; do
        local file pattern
        [[ ! -e "$conf" ]] && printf "File doesn't exist\n" && return 1
        file=${conf%%+(/)}
        file=${file##*/}
        [[ -d "$conf" ]] && file=${file}/
        pattern='!'"/${file}"
        if ! grep -Fxq "$pattern" "$HOME"/.config/.gitignore; then
            printf "%s\n" "$pattern" >>"$HOME"/.config/.gitignore
            dotfiles add "$HOME"/.config/.gitignore
        fi
        dotfiles add "$conf"
    done
}

dotbranch-mergeall() {
    local branches branch_name
    branch_name="$(dotfiles rev-parse --abbrev-ref HEAD)"
    if [[ "$branch_name" != "master" ]]; then
        printf '%s\n' "Error: Current branch is not master"
    else
        readarray -t branches < <(dotfiles for-each-ref --format='%(refname:short)' refs/heads/)
        for branch in "${branches[@]}"; do
            if [[ "$branch" != "master" ]]; then
                dotfiles checkout "$branch"
                dotfiles show
                read -p "Confirm push? [y/N] (Please review carefully)" -n 1 -r
                echo "$REPLY"
                if [[ $REPLY =~ ^[Yy]$ ]]; then
                    dotfiles merge master
                    dotfiles push
                fi
                dotfiles checkout master
            fi
        done
    fi
}
